exports.books = [
  {
    author: "J.K. Rowling",
    book_name: "Harry Potter and the Philosopher's Stone",
    publish_year: 1997,
    provider_id: 1,
  },
  {
    author: "George Orwell",
    book_name: "1984",
    publish_year: 1949,
    provider_id: 2,
  },
  {
    author: "Harper Lee",
    book_name: "To Kill a Mockingbird",
    publish_year: 1960,
    provider_id: 1,
  },
  {
    author: "J.R.R. Tolkien",
    book_name: "The Lord of the Rings",
    publish_year: 1954,
    provider_id: 3,
  },
  {
    author: "F. Scott Fitzgerald",
    book_name: "The Great Gatsby",
    publish_year: 1925,
    provider_id: 4,
  },
  {
    author: "Mark Twain",
    book_name: "Adventures of Huckleberry Finn",
    publish_year: 1884,
    provider_id: 5,
  },
  {
    author: "J.D. Salinger",
    book_name: "The Catcher in the Rye",
    publish_year: 1951,
    provider_id: 1,
  },
  {
    author: "Leo Tolstoy",
    book_name: "War and Peace",
    publish_year: 1869,
    provider_id: 2,
  },
  {
    author: "Jane Austen",
    book_name: "Pride and Prejudice",
    publish_year: 1813,
    provider_id: 3,
  },
  {
    author: "Gabriel García Márquez",
    book_name: "One Hundred Years of Solitude",
    publish_year: 1967,
    provider_id: 4,
  },
  {
    author: "Victor Hugo",
    book_name: "Les Misérables",
    publish_year: 1862,
    provider_id: 5,
  },
  {
    author: "Toni Morrison",
    book_name: "Beloved",
    publish_year: 1987,
    provider_id: 1,
  },
  {
    author: "George R.R. Martin",
    book_name: "A Game of Thrones",
    publish_year: 1996,
    provider_id: 2,
  },
  {
    author: "Stephen King",
    book_name: "The Shining",
    publish_year: 1977,
    provider_id: 3,
  },
  {
    author: "Fyodor Dostoevsky",
    book_name: "Crime and Punishment",
    publish_year: 1866,
    provider_id: 4,
  },
  {
    author: "Emily Brontë",
    book_name: "Wuthering Heights",
    publish_year: 1847,
    provider_id: 5,
  },
  {
    author: "Margaret Atwood",
    book_name: "The Handmaid's Tale",
    publish_year: 1985,
    provider_id: 1,
  },
  {
    author: "Arthur Conan Doyle",
    book_name: "The Adventures of Sherlock Holmes",
    publish_year: 1892,
    provider_id: 2,
  },
  {
    author: "Herman Melville",
    book_name: "Moby-Dick",
    publish_year: 1851,
    provider_id: 3,
  },
  {
    author: "Ray Bradbury",
    book_name: "Fahrenheit 451",
    publish_year: 1953,
    provider_id: 4,
  },
  {
    author: "Ernest Hemingway",
    book_name: "The Old Man and the Sea",
    publish_year: 1952,
    provider_id: 5,
  },
  {
    author: "Aldous Huxley",
    book_name: "Brave New World",
    publish_year: 1932,
    provider_id: 1,
  },
  {
    author: "Charles Dickens",
    book_name: "Great Expectations",
    publish_year: 1861,
    provider_id: 2,
  },
  {
    author: "John Steinbeck",
    book_name: "The Grapes of Wrath",
    publish_year: 1939,
    provider_id: 3,
  },
  {
    author: "Virginia Woolf",
    book_name: "To the Lighthouse",
    publish_year: 1927,
    provider_id: 4,
  },
  {
    author: "Mary Shelley",
    book_name: "Frankenstein",
    publish_year: 1818,
    provider_id: 5,
  },
  {
    author: "Kurt Vonnegut",
    book_name: "Slaughterhouse-Five",
    publish_year: 1969,
    provider_id: 1,
  },
  {
    author: "Jules Verne",
    book_name: "Twenty Thousand Leagues Under the Sea",
    publish_year: 1870,
    provider_id: 2,
  },
  {
    author: "Ernest Cline",
    book_name: "Ready Player One",
    publish_year: 2011,
    provider_id: 3,
  },
  {
    author: "Ken Kesey",
    book_name: "One Flew Over the Cuckoo's Nest",
    publish_year: 1962,
    provider_id: 4,
  },
  {
    author: "Charlotte Brontë",
    book_name: "Jane Eyre",
    publish_year: 1847,
    provider_id: 5,
  },
  {
    author: "F. Scott Fitzgerald",
    book_name: "Tender Is the Night",
    publish_year: 1934,
    provider_id: 1,
  },
  {
    author: "Philip K. Dick",
    book_name: "Do Androids Dream of Electric Sheep?",
    publish_year: 1968,
    provider_id: 2,
  },
  {
    author: "H.G. Wells",
    book_name: "The War of the Worlds",
    publish_year: 1898,
    provider_id: 3,
  },
  {
    author: "William Golding",
    book_name: "Lord of the Flies",
    publish_year: 1954,
    provider_id: 4,
  },
  {
    author: "Anne Frank",
    book_name: "The Diary of a Young Girl",
    publish_year: 1947,
    provider_id: 5,
  },
  {
    author: "Kazuo Ishiguro",
    book_name: "Never Let Me Go",
    publish_year: 2005,
    provider_id: 1,
  },
  {
    author: "Donna Tartt",
    book_name: "The Secret History",
    publish_year: 1992,
    provider_id: 2,
  },
  {
    author: "Sylvia Plath",
    book_name: "The Bell Jar",
    publish_year: 1963,
    provider_id: 3,
  },
  {
    author: "Lewis Carroll",
    book_name: "Alice's Adventures in Wonderland",
    publish_year: 1865,
    provider_id: 4,
  },
  {
    author: "Orson Scott Card",
    book_name: "Ender's Game",
    publish_year: 1985,
    provider_id: 5,
  },
  {
    author: "Charlotte Perkins Gilman",
    book_name: "The Yellow Wallpaper",
    publish_year: 1892,
    provider_id: 1,
  },
  {
    author: "Raymond Chandler",
    book_name: "The Big Sleep",
    publish_year: 1939,
    provider_id: 2,
  },
  {
    author: "Thomas Pynchon",
    book_name: "Gravity's Rainbow",
    publish_year: 1973,
    provider_id: 3,
  },
  {
    author: "Agatha Christie",
    book_name: "Murder on the Orient Express",
    publish_year: 1934,
    provider_id: 4,
  },
  {
    author: "John Green",
    book_name: "The Fault in Our Stars",
    publish_year: 2012,
    provider_id: 5,
  },
  {
    author: "Dan Brown",
    book_name: "The Da Vinci Code",
    publish_year: 2003,
    provider_id: 1,
  },
  {
    author: "Haruki Murakami",
    book_name: "Norwegian Wood",
    publish_year: 1987,
    provider_id: 2,
  },
  {
    author: "Yann Martel",
    book_name: "Life of Pi",
    publish_year: 2001,
    provider_id: 3,
  },
  {
    author: "J.K. Rowling",
    book_name: "Harry Potter and the Chamber of Secrets",
    publish_year: 1998,
    provider_id: 4,
  },
  {
    author: "Suzanne Collins",
    book_name: "The Hunger Games",
    publish_year: 2008,
    provider_id: 5,
  },
];
